xUAC: added AlwaysNotifyAndAskForCredentials option (Fixes #8)
dsccommunity/xSystemSecurity pull request #10
Opened 2016-10-17 14:38 UTC by machgo

Hi @kwirkykat  @Zulgrib

My PR contains:
A new option AlwaysNotifyAndAskForCredentials for xUAC which can be used to configure UAC to always ask for credentials.

Let me know if there are any issues.

2016-10-17 14:38 UTC, msftclas commented
Hi __@machgo__, I'm your friendly neighborhood Microsoft Pull Request Bot (You can call me MSBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.microsoft.com.
    </span>

TTYL, MSBOT;

2016-10-17 14:40 UTC, msftclas commented
__@machgo__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, MSBOT;

2016-11-22 20:50 UTC, eshaparmar requested changes

2016-11-22 20:50 UTC, eshaparmar commented on DSCResources/xUAC/xUAC.schema.psm1
> +        "AlwaysNotifyAndAskForCredentials"
what is the intent of this change?

2016-11-22 20:50 UTC, eshaparmar commented on DSCResources/xUAC/xUAC.schema.psm1
> +        {
'AlwaysNotifyAndAskForCredentials' is missing from the validateset in the function.

2016-11-22 20:50 UTC, eshaparmar commented on README.md
>      The dimming of your desktop is referred to as the secure desktop because other programs can't run while it's dimmed.
Also missing from the Settings bullet in the readme

2017-05-16 07:46 UTC, SwarfegaGit commented on DSCResources/xUAC/xUAC.schema.psm1
> +        {
I think this should be 1 rather than 3 since this uses the secure desktop where 3 does not.

https://msdn.microsoft.com/en-us/library/cc232761.aspx

2017-09-06 07:47 UTC, SwarfegaGit commented
Any chance of getting any movement with this PR?  I don't currently use this resource but will do once this PR is merged.

2017-10-21 00:33 UTC, kwirkykat commented
@machgo ?

2020-02-08 17:51 UTC, johlju commented
This resource is being moved to the module ComputerManagementDsc and will be deprecated in this module. These changes has hopefully been added to the new resource. Closing this PR now. Thank you for your work on this!

2020-02-08 17:51 UTC, closed without merging